version: "3.7"
services:
  mongo:
    image: mongo:4.4.10-focal
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: kaomoji-slack
    volumes:
      - kaomoji-db-data:/data/db
    networks:
      - kaomoji

  kaomoji:
    image: node:18
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    command:
      - /app/entrypoint.sh
    networks:
      - kaomoji
    env_file:
      - env_files/compose.env

volumes:
  kaomoji-db-data:

networks:
  kaomoji:
