version: "3.7"
services:
  mongo:
    image: mongo:3.6.12-xenial
    ports:
    - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: kaomoji-slack
    volumes:
    - kaomoji-db-data:/data/db
    networks:
    - kaomoji

  kaomoji:
    image: node:8.16.0-jessie
    volumes:
    - .:/app
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    command:
    - /app/entrypoint.sh
    networks:
    - kaomoji
    env_file:
    - env_files/compose.env

volumes:
  kaomoji-db-data:

networks:
  kaomoji: